export component AndroidAutoPage inherits Rectangle {
    in-out property <image> android-auto-frame;

        VerticalLayout {
        alignment: center;

            Text {
                text: "Please plug in your phone";
                font-size: 24px;
                font-weight: 700;
                horizontal-alignment: center;
                vertical-alignment: center;
        }
    }

    Image {
        source: root.android-auto-frame;
        width: parent.width;
        height: parent.height;
    }
}
