import { Divider } from "../custom-components.slint";
export component HomePage inherits VerticalLayout {
    alignment: center;

    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            spacing: 8px;
            width: 400px;

            Text {
                text: "Home";
                font-size: 24px;
                font-weight: 700;
                color: #ffffff;
            }

            Divider { }

            Text {
                text: "Hello, World!";
                font-size: 16px;
                color: #b0b0b0;
            }
        }
    }
}
