import { VerticalBox } from "std-widgets.slint";
import { Button, HorizontalDivider } from "../custom-components.slint";

export component MusicLibraryPage inherits VerticalLayout {
    in-out property <bool> dark-mode: true;
    alignment: center;

    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            spacing: 8px;
            width: 400px;

            Text {
                text: "Music Library";
                font-size: 24px;
                font-weight: 700;
                color: root.dark-mode ? #ffffff : #000000;
            }

            HorizontalDivider { }

            Text {
                text: "Hello, World!";
                font-size: 16px;
                color: root.dark-mode ? #b0b0b0 : #555555;
            }
        }
    }
}
