import { Button, HorizontalDivider } from "../custom-components.slint";

export component MusicPage inherits VerticalLayout {
    in-out property <bool> dark-mode: true;
    in-out property <bool> is-playing;
    in-out property <bool> is-loop-enabled;
    in-out property <bool> is-shuffle-enabled;
    in-out property <string> track-title;
    in-out property <string> artist-name;
    in-out property <string> album-name;
    in-out property <float> progress;
    in-out property <string> current-time;
    in-out property <string> total-time;

    callback play-pause();
    callback next-track();
    callback previous-track();
    callback toggle-loop();
    callback toggle-shuffle();
    callback set-progress(float);

    padding: 25px;
    spacing: 25px;
    alignment: space-around;

    VerticalLayout {
        spacing: 25px;

        HorizontalLayout {
            spacing: 25px;
            height: 160px;

            Rectangle {
                width: 160px;
                height: 160px;
                background: root.dark-mode ? #1e1e2e : #e0e0e0;
                border-radius: 12px;
                y: 0 - (self.height - parent.height) / 2;

                Image {
                    source: @image-url("../../assets/icons/music.svg");
                    width: parent.width * 0.4;
                    height: parent.height * 0.4;
                    colorize: root.dark-mode ? #ffffff : #555555;
                }
            }

            VerticalLayout {
                spacing: 6px;
                alignment: space-evenly;

                Text {
                    text: root.track-title;
                    font-size: 20px;
                    font-weight: 700;
                    color: root.dark-mode ? #ffffff : #1a1a1a;
                }

                Text {
                    text: root.artist-name;
                    font-size: 14px;
                    color: root.dark-mode ? #b0b0b0 : #555555;
                }

                Text {
                    text: root.album-name;
                    font-size: 12px;
                    color: root.dark-mode ? #707070 : #888888;
                }

                HorizontalLayout {
                    spacing: 12px;

                    Text {
                        text: root.current-time;
                        font-size: 11px;
                        color: root.dark-mode ? #ffffff : #1a1a1a;
                        min-width: 32px;
                        vertical-alignment: center;
                        horizontal-alignment: left;
                    }

                    Rectangle {
                        TouchArea {
                            height: 500%; // Make it easier to click
                            moved => {
                                root.progress = max(0.0, min(1.0, self.mouse-x / self.width)); // Only move the slider visually
                            }
                            pointer-event(event) => { // Not using clicked cuz that gives issues when dragging your cursor outside the TouchArea
                                if (event.kind == PointerEventKind.up) {
                                    root.progress = max(0.0, min(1.0, self.mouse-x / self.width)); // Move slider visually
                                    root.set-progress(root.progress); // Set actual progress
                                }
                                if (event.kind == PointerEventKind.down) {
                                    root.progress = max(0.0, min(1.0, self.mouse-x / self.width)); // Move slider visually
                                }
                            }
                        }

                        Rectangle {
                            width: 100%;
                            height: 6px;
                            background: root.dark-mode ? #404040 : #cccccc;
                            border-radius: 4px;
                            clip: true;

                            Rectangle {
                                x: 0px;
                                width: parent.width * root.progress;
                                background: #c20000;
                                border-radius: 4px;
                            }
                        }

                        Rectangle { // Progress ball
                            width: 15px;
                            height: 15px;
                            x: parent.width * root.progress - self.width / 2;
                            background: #c20000;
                            border-radius: 100px;
                        }
                    }

                    Text {
                        text: root.total-time;
                        font-size: 11px;
                        color: root.dark-mode ? #ffffff : #1a1a1a;
                        min-width: 32px;
                        vertical-alignment: center;
                        horizontal-alignment: right;
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: space-between;

            Rectangle {
                width: 32px;
                height: 62px;

                TouchArea {
                    width: 80px;
                    height: 80px;

                    clicked => {
                        root.toggle-shuffle();
                    }
                }

                Image {
                    source: root.is-shuffle-enabled ? @image-url("../../assets/icons/shuffle_enabled.svg") : @image-url("../../assets/icons/shuffle_disabled.svg");
                    width: 32px;
                    height: 32px;
                    colorize: root.is-shuffle-enabled ? #c20000 : root.dark-mode ? #ffffff : #555555;
                }
            }

            Rectangle {
                width: 32px;
                height: 62px;

                TouchArea {
                    width: 80px;
                    height: 80px;

                    clicked => {
                        root.previous-track();
                    }
                }

                Image {
                    source: @image-url("../../assets/icons/previous.svg");
                    width: 42px;
                    height: 42px;
                    colorize: root.dark-mode ? #ffffff : #555555;
                }
            }

            Rectangle {
                width: 32px;
                height: 62px;

                TouchArea {
                    width: 80px;
                    height: 80px;

                    clicked => {
                        root.play-pause();
                    }
                }

                Rectangle {
                    width: 62px;
                    height: 62px;
                    border-radius: 100px;
                    background: #c20000;

                    Image {
                        source: root.is-playing ? @image-url("../../assets/icons/pause.svg") : @image-url("../../assets/icons/play.svg");
                        width: 30px;
                        height: 30px;
                    }
                }
            }

            Rectangle {
                width: 32px;
                height: 62px;

                TouchArea {
                    width: 80px;
                    height: 80px;

                    clicked => {
                        root.next-track();
                    }
                }

                Image {
                    source: @image-url("../../assets/icons/next.svg");
                    width: 42px;
                    height: 42px;
                    colorize: root.dark-mode ? #ffffff : #555555;
                }
            }

            Rectangle {
                width: 32px;
                height: 62px;

                TouchArea {
                    width: 80px;
                    height: 80px;

                    clicked => {
                        root.toggle-loop();
                    }
                }

                Image {
                    source: root.is-loop-enabled ? @image-url("../../assets/icons/loop_enabled.svg") : @image-url("../../assets/icons/loop_disabled.svg");
                    width: 32px;
                    height: 32px;
                    colorize: root.is-loop-enabled ? #c20000 : root.dark-mode ? #ffffff : #555555;
                }
            }
        }
    }

    HorizontalDivider { }

    VerticalLayout {
        spacing: 10px;

        Text {
            text: "Up Next";
            font-size: 14px;
            color: root.dark-mode ? #ffffff : #1a1a1a;
            height: 20px;
        }

        Rectangle {
            TouchArea {
                width: 120%;
                height: 200%;
                clicked => {
                    root.next-track();
                }
            }

            HorizontalLayout {
                spacing: 25px;

                Rectangle {
                    width: 60px;
                    height: 60px;
                    background: root.dark-mode ? #1e1e2e : #e0e0e0;
                    border-radius: 12px;

                    Image {
                        source: @image-url("../../assets/icons/music.svg");
                        width: parent.width * 0.4;
                        height: parent.height * 0.4;
                        colorize: root.dark-mode ? #ffffff : #555555;
                    }
                }

                VerticalLayout {
                    alignment: space-evenly;

                    Text {
                        text: root.track-title;
                        font-size: 16px;
                        font-weight: 700;
                        color: root.dark-mode ? #ffffff : #1a1a1a;
                    }

                    Text {
                        text: root.artist-name;
                        font-size: 13px;
                        color: root.dark-mode ? #b0b0b0 : #555555;
                    }
                }

                Text {
                    text: ">";
                    font-size: 30px;
                    color: root.dark-mode ? #b0b0b0 : #555555;
                    vertical-alignment: center;
                    horizontal-alignment: right;
                }
            }
        }
    }
}
