import { VerticalBox } from "std-widgets.slint";
import { Button, Divider } from "../custom-components.slint";

export component SettingsPage inherits VerticalLayout {
    callback quit();

    alignment: center;

    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            spacing: 8px;
            width: 400px;

            Text {
                text: "Settings";
                font-size: 24px;
                font-weight: 700;
                color: #ffffff;
            }

            Divider { }

            Text {
                text: "Hello, World!";
                font-size: 16px;
                color: #b0b0b0;
            }

            Button {
                text: "Quit";
                height: 40px;
                font-size: 16px;
                clicked => {
                    quit();
                }
            }
        }
    }
}
