import { VerticalBox } from "std-widgets.slint";
import {
    Button,
    HorizontalDivider,
    ToggleSwitch,
} from "../custom-components.slint";

export component SettingsPage inherits VerticalLayout {
    in-out property <bool> dark-mode: true;
    in-out property <string> app-version: "Unknown";
    callback shutdown();
    callback reboot();
    callback toggle-dark-mode();

    alignment: center;

    HorizontalLayout {
        alignment: center;

        VerticalLayout {
            spacing: 8px;
            width: 400px;

            Text {
                text: "Settings";
                font-size: 24px;
                font-weight: 700;
                color: root.dark-mode ? #ffffff : #000000;
            }

            HorizontalDivider { }

            HorizontalLayout {
                alignment: start;
                spacing: 16px;

                Text {
                    text: "Dark Mode";
                    font-size: 16px;
                    color: root.dark-mode ? #b0b0b0 : #555555;
                    vertical-alignment: center;
                }

                ToggleSwitch {
                    checked: root.dark-mode;
                    clicked => {
                        root.toggle-dark-mode();
                    }
                }
            }

            HorizontalDivider { }

            Button {
                text: "Shutdown";
                height: 40px;
                font-size: 16px;
                clicked => {
                    shutdown();
                }
            }

            Button {
                text: "Reboot";
                height: 40px;
                font-size: 16px;
                clicked => {
                    reboot();
                }
            }

            HorizontalDivider { }

            Text {
                text: "rusty-dash v" + app-version;
                font-size: 12px;
                color: root.dark-mode ? #707070 : #888888;
            }
        }
    }
}
