 export component Button inherits Rectangle {
    in-out property text <=> txt.text;
    in-out property font-size <=> txt.font-size;
    in-out property text-color <=> txt.color;
    in-out property <color> background-color: #c20000;
    in-out property <color> background-color-pressed: #e10000;
    callback clicked <=> touch.clicked;

    border-radius: 6px;
    background: touch.pressed ? background-color-pressed : background-color;
    height: 40px;

    txt := Text {
        color: #ffffff;
        font-size: 13px;
        font-weight: 500;
    }

    touch := TouchArea { }
}

 export component ImageButton inherits Rectangle {
    callback clicked <=> touch.clicked;
    in-out property image <=> img.source;
    in-out property image-color <=> img.colorize;
    in-out property image-width <=> img.width;
    in-out property image-height <=> img.height;

    img := Image {
        source: @image-url("../assets/icons/home.svg");
        colorize: #ffffff;
        width: 25px;
        height: 25px;
    }

    touch := TouchArea { }
}

export component ToggleSwitch inherits Rectangle {
    callback clicked <=> touch.clicked;
    in-out property <bool> checked;

    width: 50px;
    height: 28px;
    border-radius: 14px;
    background: root.checked ? #c20000 : #555555;

    Rectangle {
        width: 24px;
        height: 24px;
        border-radius: 12px;
        background: #ffffff;
        x: root.checked ? parent.width - self.width - 2px : 2px;
        y: 2px;
    }

    touch := TouchArea { }
}

export component HorizontalDivider inherits Rectangle {
    height: 1px;
    background: #80808050;
}
