import { MusicPage } from "./pages/music.slint";
import { AndroidAutoPage } from "./pages/android_auto.slint";
import { SettingsPage } from "./pages/settings.slint";
import {
    Button,
    ImageButton,
    HorizontalDivider,
    VerticalDivider,
} from "./custom-components.slint";

component SidebarItem inherits Rectangle {
    in-out property <image> image;
    in-out property <bool> active;
    callback clicked;

    width: 100px;
    height: 80px;

    background: active ? @linear-gradient(90deg, #e5393522 0%, #12121200 100%) : transparent;

    Rectangle {
        x: 0;
        width: 4px;
        height: 50%;
        y: (parent.height - self.height) / 2;
        background: active ? #e53935 : transparent;
        border-radius: 2px;
    }

    ImageButton {
        image: root.image;
        image-width: 42px;
        image-height: 42px;
        image-color: active ? #e53935 : #888888;
        clicked => {
            root.clicked();
        }
    }
}

export component AppWindow inherits Window {
    in-out property <int> current-page: 0;

    in-out property <bool> is-playing: false;
    in-out property <bool> is-loop-enabled: false;
    in-out property <bool> is-shuffle-enabled: false;

    in-out property <string> track-title: "Title";
    in-out property <string> artist-name: "Artist";
    in-out property <string> album-name: "Album";

    in-out property <float> progress: 0.0;
    in-out property <string> time: "0:00 / 0:00";

    in-out property <image> android-auto-frame;

    callback play-pause();
    callback next-track();
    callback previous-track();
    callback toggle-loop();
    callback toggle-shuffle();
    callback set-progress(float);

    in-out property <string> app-version: "Unknown";

    callback shutdown();
    callback reboot();
    callback handle_android_auto_touch(int, int, int);

    title: "Rusty Dash";
    // Hardcoded because this is the raspberry pi 7 inch touchscreen resolution
    // I don't wanna mess with scaling, nobody is gonna use this project anyway
    width: 800px;
    height: 480px;

    background: #121212;

    HorizontalLayout {
        VerticalLayout {
            width: 100px;
            alignment: center;
            spacing: 16px;
            padding-top: 16px;
            padding-bottom: 24px;

            SidebarItem {
                image: @image-url("../assets/icons/music.svg");
                active: root.current-page == 0;
                clicked => {
                    root.current-page = 0;
                }
            }

            SidebarItem {
                image: @image-url("../assets/icons/android_auto.svg");
                active: root.current-page == 1;
                clicked => {
                    root.current-page = 1;
                }
            }

            SidebarItem {
                image: @image-url("../assets/icons/settings.svg");
                active: root.current-page == 2;
                clicked => {
                    root.current-page = 2;
                }
            }
        }

        VerticalDivider { }

        Rectangle {
            if root.current-page == 0: MusicPage {
                is-playing: root.is-playing;
                is-loop-enabled: root.is-loop-enabled;
                is-shuffle-enabled: root.is-shuffle-enabled;

                track-title: root.track-title;
                artist-name: root.artist-name;
                album-name: root.album-name;

                progress: root.progress;
                time: root.time;

                play-pause => {
                    root.play-pause();
                }
                next-track => {
                    root.next-track();
                }
                previous-track => {
                    root.previous-track();
                }
                toggle-loop => {
                    root.toggle-loop();
                }
                toggle-shuffle => {
                    root.toggle-shuffle();
                }
                set-progress(progress) => {
                    root.set-progress(progress);
                }
            }

            if root.current-page == 1: AndroidAutoPage {
                android-auto-frame: root.android-auto-frame;
                handle_touch(x, y, action) => {
                    root.handle_android_auto_touch(x, y, action);
                }
            }

            if root.current-page == 2: SettingsPage {
                app-version: root.app-version;
                shutdown => {
                    root.shutdown();
                }
                reboot => {
                    root.reboot();
                }
            }
        }
    }
}
