import { HomePage } from "./pages/home.slint";
import { MusicPage } from "./pages/music.slint";
import { AndroidAutoPage } from "./pages/android_auto.slint";
import { SettingsPage } from "./pages/settings.slint";
import { Button, ImageButton } from "./custom-components.slint";

export component AppWindow inherits Window {
    title: "Rusty Dash";
    full-screen: true;

    background: #121212;

    in-out property <int> current-page: 0;

    in-out property <bool> is-playing: false;
    in-out property <bool> is-loop-enabled: false;
    in-out property <bool> is-shuffle-enabled: false;

    in-out property <string> track-title: "Title";
    in-out property <string> artist-name: "Artist";
    in-out property <string> album-name: "Album";

    in-out property <image> android-auto-frame;

    callback play-pause();
    callback next-track();
    callback previous-track();
    callback toggle-loop();
    callback toggle-shuffle();

    callback shutdown();

    HorizontalLayout {
        VerticalLayout {
            ImageButton {
                image: @image-url("../assets/icons/home.svg");
                image-width: 80px;
                image-height: 80px;
                image-color: root.current-page == 0 ? #c20000 : #ffffff;
                width: 100px;
                // height: 100px;
                clicked => {
                    root.current-page = 0;
                }
            }

            ImageButton {
                image: @image-url("../assets/icons/music.svg");
                image-width: 80px;
                image-height: 80px;
                image-color: root.current-page == 1 ? #c20000 : #ffffff;
                width: 100px;
                // height: 100px;
                clicked => {
                    root.current-page = 1;
                }
            }

            ImageButton {
                image: @image-url("../assets/icons/android_auto.svg");
                image-width: 80px;
                image-height: 80px;
                image-color: root.current-page == 2 ? #c20000 : #ffffff;
                width: 100px;
                // height: 100px;
                clicked => {
                    root.current-page = 2;
                }
            }

            ImageButton {
                image: @image-url("../assets/icons/settings.svg");
                image-width: 80px;
                image-height: 80px;
                image-color: root.current-page == 3 ? #c20000 : #ffffff;
                width: 100px;
                // height: 100px;
                clicked => {
                    root.current-page = 3;
                }
            }
        }

        Rectangle {
            if root.current-page == 0: HomePage { }

            if root.current-page == 1: MusicPage {
                is-playing: root.is-playing;
                is-loop-enabled: root.is-loop-enabled;
                is-shuffle-enabled: root.is-shuffle-enabled;

                track-title: root.track-title;
                artist-name: root.artist-name;
                album-name: root.album-name;

                play-pause => {
                    root.play-pause();
                }
                next-track => {
                    root.next-track();
                }
                previous-track => {
                    root.previous-track();
                }
                toggle-loop => {
                    root.toggle-loop();
                }
                toggle-shuffle => {
                    root.toggle-shuffle();
                }
            }

            if root.current-page == 2: AndroidAutoPage {
                android-auto-frame: root.android-auto-frame;
            }

            if root.current-page == 3: SettingsPage {
                shutdown => {
                    root.shutdown();
                }
            }
        }
    }
}
