import { MusicPage } from "./pages/music.slint";
import { MusicLibraryPage } from "./pages/music_library.slint";
import { AndroidAutoPage } from "./pages/android_auto.slint";
import { SettingsPage } from "./pages/settings.slint";
import {
    Button,
    ImageButton,
    HorizontalDivider,
} from "./custom-components.slint";

component SidebarItem inherits Rectangle {
    in-out property <image> image;
    in-out property <bool> active;
    in-out property <bool> dark-mode: true;
    callback clicked;

    width: 100px;
    height: 80px;

    background: active ? @linear-gradient(90deg, #e5393522 0%, #12121200 100%) : transparent;

    Rectangle {
        x: 0;
        width: 4px;
        height: 50%;
        y: (parent.height - self.height) / 2;
        background: active ? #e53935 : transparent;
        border-radius: 2px;
    }

    ImageButton {
        image: root.image;
        image-width: 42px;
        image-height: 42px;
        image-color: active ? #e53935 : root.dark-mode ? #888888 : #666666;
        clicked => {
            root.clicked();
        }
    }
}

export component AppWindow inherits Window {
    in-out property <int> current-page: 0;

    in-out property <bool> is-playing: false;
    in-out property <bool> is-loop-enabled: false;
    in-out property <bool> is-shuffle-enabled: false;

    in-out property <string> track-title: "Title";
    in-out property <string> artist-name: "Artist";
    in-out property <string> album-name: "Album";

    in-out property <string> next-track-title: "Next Track";
    in-out property <string> next-track-artist: "Next Artist";

    in-out property <float> progress: 0.0;
    in-out property <string> current-time: "0:00";
    in-out property <string> total-time: "0:00";

    in-out property <image> android-auto-frame;

    in-out property <bool> dark-mode: true;

    callback play-pause();
    callback next-track();
    callback previous-track();
    callback toggle-loop();
    callback toggle-shuffle();
    callback set-progress(float);

    in-out property <string> app-version: "Unknown";

    callback shutdown();
    callback reboot();
    callback toggle-dark-mode();
    callback handle_android_auto_touch(int, int, int);

    title: "Rusty Dash";
    // Hardcoded because this is the raspberry pi 7 inch touchscreen resolution
    // I don't wanna mess with scaling, nobody is gonna use this project anyway
    width: 800px;
    height: 480px;

    background: root.dark-mode ? #000000 : #e8e8e8;

    HorizontalLayout {
        spacing: 10px;
        padding: 10px;

        Rectangle {
            background: root.dark-mode ? #121212 : #ffffff;
            border-radius: 12px;
            border-width: 1px;
            border-color: root.dark-mode ? #70707084 : #c8c8c880;

            VerticalLayout {
                width: 100px;
                alignment: center;
                spacing: 16px;
                padding-top: 16px;
                padding-bottom: 24px;

                SidebarItem {
                    image: @image-url("../assets/icons/music.svg");
                    dark-mode: root.dark-mode;
                    active: root.current-page == 0;
                    clicked => {
                        root.current-page = 0;
                    }
                }

                SidebarItem {
                    image: @image-url("../assets/icons/library.svg");
                    dark-mode: root.dark-mode;
                    active: root.current-page == 1;
                    clicked => {
                        root.current-page = 1;
                    }
                }

                SidebarItem {
                    image: @image-url("../assets/icons/android_auto.svg");
                    dark-mode: root.dark-mode;
                    active: root.current-page == 2;
                    clicked => {
                        root.current-page = 2;
                    }
                }

                SidebarItem {
                    image: @image-url("../assets/icons/settings.svg");
                    dark-mode: root.dark-mode;
                    active: root.current-page == 3;
                    clicked => {
                        root.current-page = 3;
                    }
                }
            }
        }

        Rectangle {
            background: root.dark-mode ? #121212 : #ffffff;
            border-radius: 12px;
            border-width: 1px;
            border-color: root.dark-mode ? #70707084 : #c8c8c880;

            if root.current-page == 0: MusicPage {
                dark-mode: root.dark-mode;
                is-playing: root.is-playing;
                is-loop-enabled: root.is-loop-enabled;
                is-shuffle-enabled: root.is-shuffle-enabled;

                track-title: root.track-title;
                artist-name: root.artist-name;
                album-name: root.album-name;

                next-track-title: root.next-track-title;
                next-track-artist: root.next-track-artist;

                progress: root.progress;
                current-time: root.current-time;
                total-time: root.total-time;

                play-pause => {
                    root.play-pause();
                }
                next-track => {
                    root.next-track();
                }
                previous-track => {
                    root.previous-track();
                }
                toggle-loop => {
                    root.toggle-loop();
                }
                toggle-shuffle => {
                    root.toggle-shuffle();
                }
                set-progress(progress) => {
                    root.set-progress(progress);
                }
            }

            if root.current-page == 1: MusicLibraryPage {
                dark-mode: root.dark-mode;
            }

            if root.current-page == 2: AndroidAutoPage {
                android-auto-frame: root.android-auto-frame;
                handle_touch(x, y, action) => {
                    root.handle_android_auto_touch(x, y, action);
                }
            }

            if root.current-page == 3: SettingsPage {
                dark-mode: root.dark-mode;
                app-version: root.app-version;
                toggle-dark-mode => {
                    root.toggle-dark-mode();
                }
                shutdown => {
                    root.shutdown();
                }
                reboot => {
                    root.reboot();
                }
            }
        }
    }
}
