# Enable or disable dash, if disabled it will start a getty on tty1
ENABLE_DASH=true

# The backend to use for Slint, see the url below for other choices.
# https://docs.slint.dev/latest/docs/slint/guide/backends-and-renderers/backend_linuxkms/
SLINT_BACKEND=linuxkms-software

# The scale factor for Slint, set lower if buttons are outside the screen, set higher if the UI is too small.
SLINT_SCALE_FACTOR=1