[package]
name = "rusty-dash"
version = "0.0.21"
edition = "2024"
default-run = "rusty-dash"

[[bin]]
name = "screenshot"
path = "src/bin/screenshot.rs"

[dependencies]
android-auto = {
  git = "https://github.com/AlexJonker/android-auto",
  features = ["usb", "wireless"]
}
async-trait = "0.1.89"
bluetooth-rust = { version = "0.4.1", features = ["async"] }
cpal = "0.18.1"
image = "0.25.10"
log = "0.4.33"
nmrs = "3.3.0"
openh264 = "0.9.3"
ringbuf = "0.5.0"
simple_logger = "5.2.0"
slint = { version = "1.17.0", features = ["backend-linuxkms"] }
system_shutdown = "4.1.0"
tokio = { version = "1.52.3", features = ["full"] }
zbus = "5.16.0"
zvariant = "5.12.0"

[build-dependencies]
slint-build = "1.17.0"

[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1

[profile.screenshot]  # Faster compile time
inherits = "release"
opt-level = 0
lto = false
codegen-units = 16

[profile.screenshot.package."*"]
opt-level = 0
