name: Build and Release

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  get-version:
    name: Get Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout dash
        uses: actions/checkout@main
        with:
          ref: "main"

      - name: Get version
        id: get_version
        run: echo "version=$(grep '^version' dash/Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')" >> $GITHUB_OUTPUT

  compile-arm64:
    name: Compile Dashboard arm64
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout dash
        uses: actions/checkout@main
        with:
          ref: "main"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libfontconfig1-dev protobuf-compiler libgbm-dev libxkbcommon-dev libudev-dev libseat-dev libinput-dev

      - uses: Swatinem/rust-cache@master
        with:
          prefix-key: "arm64-build"

      - name: Build dashboard
        run: |
          cd dash
          cargo build --release

      - name: Compress binary
        run: xz -c dash/target/release/rusty-dash > rusty-dash-arm64.xz

      - name: Upload binary
        uses: actions/upload-artifact@main
        with:
          name: rusty-dash-binary-arm64
          path: rusty-dash-arm64.xz

  compile-amd64:
    name: Compile Dashboard amd64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dash
        uses: actions/checkout@main
        with:
          ref: "main"

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libfontconfig1-dev protobuf-compiler libgbm-dev libxkbcommon-dev libudev-dev libseat-dev libinput-dev

      - uses: Swatinem/rust-cache@master
        with:
          prefix-key: "amd64-build"

      - name: Build dashboard
        run: |
          cd dash
          cargo build --release

      - name: Compress binary
        run: xz -c dash/target/release/rusty-dash > rusty-dash-amd64.xz

      - name: Upload binary
        uses: actions/upload-artifact@main
        with:
          name: rusty-dash-binary-amd64
          path: rusty-dash-amd64.xz

  release-binary:
    name: Release Binaries
    needs: [get-version, compile-arm64, compile-amd64]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          ref: "main"

      - uses: actions/download-artifact@main
        with:
          name: rusty-dash-binary-arm64

      - uses: actions/download-artifact@main
        with:
          name: rusty-dash-binary-amd64

      - name: Release dash binary
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ format('v{0}', needs.get-version.outputs.version) }}
          name: ${{ format('v{0}', needs.get-version.outputs.version) }}
          generate_release_notes: true
          files: |
            rusty-dash-arm64.xz
            rusty-dash-amd64.xz

  build-pi-image:
    name: Build RPi Image
    runs-on: ubuntu-24.04-arm
    needs: [get-version, compile-arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Download binary
        uses: actions/download-artifact@main
        with:
          name: rusty-dash-binary-arm64

      - name: Decompress binary
        run: xz -d rusty-dash-arm64.xz

      - name: Create custom stage
        run: |
          mkdir -p custom-stage/01-customization/files/usr/local/bin

          cp -r ./src/. custom-stage/01-customization/files/
          cp rusty-dash-arm64 custom-stage/01-customization/files/usr/local/bin/rusty-dash

          cat > custom-stage/01-customization/00-run.sh <<-'EOF'
          #!/bin/bash -e
          cp -rp files/* "${ROOTFS_DIR}/"
          EOF

          cat > custom-stage/01-customization/00-run-chroot.sh <<-'EOF'
          #!/bin/bash -e
          apt-get update
          apt-get install -y --no-install-recommends libfontconfig1 libgbm1 libxkbcommon0 libudev1 libseat1 libinput10

          chown root:root /usr/local/bin/rusty-dash
          chmod 755 /usr/local/bin/rusty-dash
          echo "root:root" | chpasswd

          mkdir -p /storage/music
          chmod -R 777 /storage

          systemctl enable startup.service
          systemctl disable getty@tty1.service
          EOF

          cat > custom-stage/prerun.sh <<-'EOF'
          #!/bin/bash -e
          if [ ! -d "${ROOTFS_DIR}" ]; then
            copy_previous
          fi
          EOF

          chmod +x custom-stage/prerun.sh
          chmod +x custom-stage/01-customization/00-run.sh
          chmod +x custom-stage/01-customization/00-run-chroot.sh

      - uses: usimd/pi-gen-action@main
        id: build
        with:
          apt-proxy: ""
          compression: xz
          compression-level: 6
          disable-first-boot-user-rename: 1
          docker-opts: ""
          enable-cloud-init: 0
          enable-noobs: false
          enable-ssh: 1
          export-last-stage-only: true
          extra-host-dependencies: ""
          extra-host-modules: ""
          github-token: ${{ github.token }}
          hostname: shitbox
          image-name: "rusty-dash-${{ needs.get-version.outputs.version }}-arm64"
          increase-runner-disk-size: false
          keyboard-keymap: us
          keyboard-layout: English (US)
          locale: en_US.UTF-8
          password: "driver"
          pi-gen-dir: pi-gen
          pi-gen-release: Raspberry Pi reference
          pi-gen-repository: RPi-Distro/pi-gen
          pi-gen-version: arm64
          pubkey-only-ssh: 0
          pubkey-ssh-first-user: ""
          release: trixie
          setfcap: ""
          stage-list: stage0 stage1 stage2 ./custom-stage
          enable-pigen-cache: true
          temp-repo: ""
          timezone: Europe/Brussels
          username: driver
          verbose-output: false
          wpa-country: ""
          wpa-essid: ""
          wpa-password: ""

      - uses: actions/upload-artifact@main
        with:
          name: rusty-dash-image
          path: ${{ steps.build.outputs.image-path }}

  release-image:
    name: Release RPi Image
    needs: [get-version, build-pi-image]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          ref: "main"

      - uses: actions/download-artifact@main
        with:
          name: rusty-dash-image

      - name: Release arm64 image
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{ format('v{0}', needs.get-version.outputs.version) }}
          name: ${{ format('v{0}', needs.get-version.outputs.version) }}
          overwrite_files: true
          files: |
            image*.img.xz

  update-screenshots:
    name: Update Screenshots
    runs-on: ubuntu-latest
    needs: [get-version, release-image]

    steps:
      - name: Checkout dash
        uses: actions/checkout@main
        with:
          ref: "main"

      - uses: Swatinem/rust-cache@master
        with:
          prefix-key: "screenshots"

      - name: Generate screenshots
        run: |
          cd dash
          cargo run --profile screenshot --bin screenshot

      - name: Commit screenshots
        run: |
          git config user.name "Rusty Dash"
          git add -A
          git diff --staged --quiet || (git commit -m "Update screenshots for release v${{ needs.get-version.outputs.version }}" && git push)
